//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorLifetimeApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensorLifetimeApp.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of Sensor Activation.
        /// </summary>
        public static string ActiveSensorProbability {
            get {
                return ResourceManager.GetString("ActiveSensorProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Capacity.
        /// </summary>
        public static string BatteryCapacity {
            get {
                return ResourceManager.GetString("BatteryCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        public static string Coverage {
            get {
                return ResourceManager.GetString("Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Under the Path.
        /// </summary>
        public static string CreatedUnderPath {
            get {
                return ResourceManager.GetString("CreatedUnderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Find.
        /// </summary>
        public static string FileNotFind {
            get {
                return ResourceManager.GetString("FileNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Empty XML File.
        /// </summary>
        public static string GenerateEmptyFile {
            get {
                return ResourceManager.GetString("GenerateEmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load State.
        /// </summary>
        public static string LoadState {
            get {
                return ResourceManager.GetString("LoadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rand Sensors.
        /// </summary>
        public static string RandSensors {
            get {
                return ResourceManager.GetString("RandSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        public static string Rebuild {
            get {
                return ResourceManager.GetString("Rebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        public static string SaveImage {
            get {
                return ResourceManager.GetString("SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save State.
        /// </summary>
        public static string SaveState {
            get {
                return ResourceManager.GetString("SaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Under the Path.
        /// </summary>
        public static string SaveUnderPath {
            get {
                return ResourceManager.GetString("SaveUnderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Count.
        /// </summary>
        public static string SensorCount {
            get {
                return ResourceManager.GetString("SensorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Radius.
        /// </summary>
        public static string SensorRadius {
            get {
                return ResourceManager.GetString("SensorRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show POIs.
        /// </summary>
        public static string ShowPOI {
            get {
                return ResourceManager.GetString("ShowPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Lifetime GUI.
        /// </summary>
        public static string TitleMainWindows {
            get {
                return ResourceManager.GetString("TitleMainWindows", resourceCulture);
            }
        }
    }
}
